eclipse/titan.core

README.linux

Revert "Update README.linux"

---

titan_executor_api/TITAN_Executor_API/create_jni_header.sh

Signed-off-by: earplov <arpad.lovassy@ericsson.com>

Fixing script comment

---

titan_executor_api/TITAN_Executor_API/create_jni_header.sh
titan_executor_api/TITAN_Executor_API/readme.txt
titan_executor_api/TITAN_Executor_API_test/readme.txt

Signed-off-by: earplov <arpad.lovassy@ericsson.com>

Fix Titan Executor API test readme

---

README.linux

Please let my changes in

---

Makefile.cfg

Please accept my changes

---

README.linux

Typo corrected in README.linux

Typo corrected in README.linux

---

compiler2/AST.cc

Signed-off-by: Botond Baranyi <botond.baranyi@ericsson.com>

Just a test

---

core/Event_Handler.hh

Signed-off-by: Naum Spaseski <naum.spaseski@eglobalmark.com>

Added file descriptor set library (Cygwin bug)

---

regression_test/XML/XmlWorkflow/XmlTest_expectedTtcns/www_example_org_list_complextype_e.ttcn
regression_test/XML/XmlWorkflow/src/xmlTest.prj
regression_test/XML/XmlWorkflow/src/xmlTest_Testcases.ttcn
regression_test/XML/XmlWorkflow/xsd/list_complextype.xsd
xsdconvert/ComplexType.cc
xsdconvert/ComplexType.hh

xsd2ttcn: fixed list generation

---

compiler2/AST.cc
compiler2/AST.hh
compiler2/DebuggerStuff.cc
compiler2/DebuggerStuff.hh
compiler2/Makefile
compiler2/Setting.cc
compiler2/Type.hh
compiler2/asn1/AST_asn1.cc
compiler2/asn1/AST_asn1.hh
compiler2/main.cc
compiler2/main.hh
compiler2/ttcn3/AST_ttcn3.cc
compiler2/ttcn3/AST_ttcn3.hh
compiler2/ttcn3/Statement.cc
core/Basetype.hh
core/Debugger.cc
core/Debugger.hh
core/Makefile
core/Runtime.cc
core/TTCN3.hh

Signed-off-by: Botond Baranyi <botond.baranyi@ericsson.com>

Debugger - Stage 1 (artf511247)

---

README.cygwin

Change-Id: I53f80c93272a757deeffd36c397cb7e6523b8bb6
Signed-off-by: balaskoa <jeno.balasko@ericsson.com>

just editorial change

---

compiler2/Value.cc
compiler2/Value.hh
compiler2/ttcn3/AST_ttcn3.cc
compiler2/ttcn3/Templatestuff.cc
compiler2/ttcn3/Templatestuff.hh
compiler2/ttcn3/TtcnTemplate.cc
regression_test/compileonly/Makefile
regression_test/compileonly/defaultParamUsageBeforeDecl/A.ttcn
regression_test/compileonly/defaultParamUsageBeforeDecl/B.ttcn
regression_test/compileonly/defaultParamUsageBeforeDecl/Makefile

Change-Id: Ifad00e6719e4a0587314192f8e0695f5bec72048
Signed-off-by: Botond Baranyi <botond.baranyi@ericsson.com>

Fixed code generation error for parameter default values (artf724695)

---

conformance_test/negative_tests/05_basic_language_elements.script
conformance_test/negative_tests/06_types_and_values.script
conformance_test/negative_tests/07-14_folder.script
conformance_test/negative_tests/08_empty_modules.script
conformance_test/negative_tests/15_templates.script
conformance_test/negative_tests/16-20_folders.script
conformance_test/negative_tests/21_configuration_operations.script
conformance_test/negative_tests/22_communication_operations.script
conformance_test/negative_tests/23-27-B_folders.script
conformance_test/negative_tests/24-26_misc_verdict.script
conformance_test/negative_tests/README.txt
conformance_test/negative_tests/SAtester.pl
conformance_test/negative_tests/Temp.ttcn
conformance_test/negative_tests/run_test_all

Signed-off-by: ethbaat <jeno.balasko@ericsson.com>

Added conformance_test/negative_tests

---

hello/Makefile

Signed-off-by: ethbaat <jeno.balasko@ericsson.com>

Forward LD & CXXFLAGS to hello/Makefile (req: Thomas Herrlin)

---

core/Error.cc

Signed-off-by: ethbaat <jeno.balasko@ericsson.com>

Fix Solaris x86-64 support (req: Thomas Herrlin)

---

Makefile.cfg

Removed duplicated JDKDIR variable

---

etc/scripts/ttcn3_archive.pl

Placed #!/usr/bin/perl before the header section

---

compiler2/makefile.c
regression_test/RAW/Examples/SCCP_typedefs.ttcn

Corrected typo (sytem > system)

---

etc/scripts/ttcn3_archive.pl

Corrected typo in ttcn3_archive.pl

---

makefiles/Makefile.personal.tcclab7

Added Makefile.personal for a new CI server

---

function_test/Semantic_Analyser/ver/high_titan_SE.ttcn

Signed-off-by: balaskoa <jeno.balasko@ericsson.com>

version test bug fixed

---

Makefile

Modified make check behavior

---

mctr2/editline/libedit/config.guess
mctr2/editline/libedit/config.sub

Updated timestamps

---

repgen/ttcn3_logfilter.1

Corrected not defined macro

---

common/new.cc

correcting error when compiling with clang

---

compiler2/ttcn3/AST_ttcn3.cc
compiler2/ttcn3/AST_ttcn3.hh
compiler2/ttcn3/Statement.cc
core/Communication.cc
core/Communication.hh
core/DebugCommands.hh
core/Debugger.cc
core/Debugger.hh
core/Makefile
core/Message_types.hh
core/Runtime.cc
core/Textbuf.cc
core/Textbuf.hh
mctr2/cli/Cli.cc
mctr2/mctr/MainController.cc
mctr2/mctr/MainController.h

Change-Id: I0be2f63e69743d2661ad1d4359c55d9e758b9e26
Signed-off-by: Botond Baranyi <botond.baranyi@ericsson.com>

Debugger - Stage 2 (artf511247)

---

compiler2/Value.cc
compiler2/Value.hh
compiler2/ttcn3/compiler.l
compiler2/ttcn3/compiler.y
core/Communication.hh
core/Runtime.cc
core/Runtime.hh
regression_test/Makefile
regression_test/hostid/Hostid.ttcn
regression_test/hostid/Makefile

added hostid function (artf724006)

---

core/Runtime.cc

hostid fix on solaris

---

core/Runtime.cc

hostid fix on solaris v2

---

core/Runtime.cc

clang specific define in Runtime.cc

---

regression_test/XML/XmlWorkflow/XmlTest_expectedTtcns/www_example_org_enumeration_restriction3_e.ttcn
regression_test/XML/XmlWorkflow/src/xmlTest.prj
regression_test/XML/XmlWorkflow/src/xmlTest_Testcases.ttcn
regression_test/XML/XmlWorkflow/xsd/enumeration_restriction3.xsd
xsdconvert/ComplexType.cc
xsdconvert/SimpleType.cc

https://bugs.eclipse.org/bugs/show_bug.cgi?id=494987

xsd2ttcn: corrected enumeration restriction (bug 494987)

---

regression_test/commProcedure/ProcPort.ttcn

Signed-off-by: balaskoa <jeno.balasko@ericsson.com>

Only naming convention and indentation cahnged in a test

---

regression_test/cfgFile/module_parameters/references/Makefile

Signed-off-by: balaskoa <jeno.balasko@ericsson.com>

A.asn has been added to cfgFile/module_params test

---

conformance_test/negative_tests/15_templates.script

Added negative tests

---

conformance_test/core_language_tests/negative_tests/21_configuration_operations.script

Corrected negative test

---

conformance_test/core_language_tests/negative_tests/SAtester.pl
conformance_test/core_language_tests/negative_tests/run_test_all

Corrected path

---

conformance_test/core_language_tests/negative_tests/22_communication_operations.script

Corrected negative tests

---

conformance_test/core_language_tests/negative_tests/05_basic_language_elements.script
conformance_test/core_language_tests/negative_tests/06_types_and_values.script
conformance_test/core_language_tests/negative_tests/07-14_folder.script
conformance_test/core_language_tests/negative_tests/08_empty_modules.script
conformance_test/core_language_tests/negative_tests/15_templates.script
conformance_test/core_language_tests/negative_tests/16-20_folders.script
conformance_test/core_language_tests/negative_tests/21_configuration_operations.script
conformance_test/core_language_tests/negative_tests/22_communication_operations.script
conformance_test/core_language_tests/negative_tests/23-27-B_folders.script
conformance_test/core_language_tests/negative_tests/24-26_misc_verdict.script

Minor name changes in negative conformance tests

---

compiler2/Type.cc
compiler2/Type_codegen.cc
regression_test/compileonly/Makefile
regression_test/compileonly/typeDescrGenWIthNoXER/Makefile
regression_test/compileonly/typeDescrGenWIthNoXER/typeDescrGenWIthNoXER.ttcn
regression_test/templateConcat/TemplateConcatChar.ttcn

Fixed code generation for list and array types with JSON encoding

---

conformance_test/core_language_tests/negative_tests/05_basic_language_elements.script
conformance_test/core_language_tests/positive_tests/21_configuration_operations/2103_test_component_operations/210306_running_operation/Sem_210306_running_operation_001.ttcn
conformance_test/core_language_tests/positive_tests/21_configuration_operations/2103_test_component_operations/210306_running_operation/Sem_210306_running_operation_002.ttcn

Corrected tests

---

core/Runtime.cc

Signed-off-by: izaingrid <farkas94ingi@gmail.com>

removed unused row

---

compiler2/ttcn3/port.c

Signed-off-by: izaingrid <farkas94ingi@gmail.com>

minor formatting for port

---

README.linux

Signed-off-by: Tamas Fekete <fektom@gmail.com>

JNI installation example of README.linux file has been corrigated

---

core/LegacyLogger.cc
core/LoggerPluginManager.cc

Signed-off-by: Gergo Ujhelyi <ujhelyi.gergo@ericsson.com>

Bug 563289 - Fixed timestamp problem after 2038

---

docker/README.txt

Signed-off-by: Elemer Lelik <elemer.lelik@ericsson.com>

Changes in docker/README.txt

---

function_test/Tools/SAtester.pl

Signed-off-by: Adam Knapp <knappadam5@gmail.com>

Function tests timeout increased
